---
#
# main.yml - handlers  to start, stop, and restart services.
#

- name: Start MySQL
  ansible.builtin.systemd:
    name: mysql
    state: started
    enabled: yes
  when: ansible_hostname == "replica" or ansible_hostname == "etlreplica" or ansible_hostname == "primary"
  
- name: Restart MySQL
  ansible.builtin.systemd:
    name: mysql
    state: restarted
  when: ansible_hostname == "replica" or ansible_hostname == "etlreplica" or ansible_hostname == "primary"