---
#
# main.yml - handlers  to start, stop, and restart services.
#


- name: Start MySQL
  ansible.builtin.systemd:
    name: mysql
    state: started
  when: ansible_hostname == "replica" or ansible_hostname == "etlreplica"

- name: Stop MySQL
  ansible.builtin.systemd:
    name: mysql
    state: stopped
  when: ansible_hostname == "replica" or ansible_hostname == "etlreplica"

- name: Restart MySQL
  ansible.builtin.systemd:
    name: mysql
    state: restarted
  when: ansible_hostname == "replica" or ansible_hostname == "etlreplica"
  
