---

#
# post-install.yml - Playbook to add some things after the installs have completed.
#

- name: Copy .my.cnf file with root password credentials
  ansible.builtin.template:
    src: templates/.my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  when: ansible_hostname != "proxysql"

- name: Create backup dir under /root
  ansible.builtin.file:
    name: '/root/backup'
    owner: root
    group: root
    mode: 0750
    state: directory
  when: ansible_hostname != "proxysql"

- name: Download Orchestrator Client with checksum (sha256)
  ansible.builtin.get_url:
    url: https://github.com/openark/orchestrator/releases/download/v3.2.6/orchestrator-client_3.2.6_amd64.deb
    dest: /tmp/orchestrator-client_3.2.6_amd64.deb
    checksum: sha256:53b5bc59fe94850163e84a0eacf035c5a82a1c1eb7e957894da81492e4f0e232
    mode: '0644'
    force: true
  when: ansible_hostname != "orchestrator"

- name: Install Orchestrator Client
  ansible.builtin.apt:
    deb: /tmp/orchestrator-client_3.2.6_amd64.deb
    state: present
  when: ansible_hostname != "orchestrator"

- name: Install | percona-toolkit | xtrabackup
  ansible.builtin.apt:
    pkg:
    - percona-toolkit
    - percona-xtrabackup-80
    - qpress
    - pv
  when: ansible_hostname != "proxysql"

- name: Sudoers Add User
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    backup: true
    regexp: '^klarsen'
    line: 'klarsen ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  tags: sudoers
      
- name: Restart MyQSL
  ansible.builtin.systemd:
    name: mysql
    state: restarted
  when: ansible_hostname == "primary"
  tags: mysql
      
- name: Generate file
  blockinfile:
    backup: yes
    path: /etc/hosts
    block: |
      {% for host in groups['all'] %} 
      {{ hostvars[host]['ansible_facts']['enp0s8']['ipv4']['address'] }} {{ hostvars[host]['ansible_facts']['fqdn'] }} {{ hostvars[host]['ansible_facts']['hostname'] }} 
      {% endfor %}
  register: result
  tags: hosts

- name: print result
  ansible.builtin.debug:
    msg: "{{ result }}"
  tags: hosts



- include_tasks: usermaint.yml