---
#
# pre-install.yml - Playbook to add some things before the main install.
#

  - name: Ensure the timeezone is set to utc 
    ansible.builtin.file: 
      src: /usr/share/zoneinfo/UTC
      dest: /etc/localtime
      state: link

  - name: System, install some base packages
    ansible.builtin.apt: 
      name:
        [ 'vim',
          'gnupg2',
          'wget',
          'curl',
          'screen',
          'rsync',
          'debconf-utils',
          'python3-pymysql' ]
      state: present 

  - name: Mount a device by label
    mount:
      path: /vagrant
      src: vagrant
      fstype: vboxsf
      state: mounted

  - name: download the Percona repo
    get_url:
      url:  https://repo.percona.com/apt/percona-release_latest.jammy_all.deb
      dest: /tmp/percona-release_latest.jammy_all.deb
      mode: '0644'
      
  - name: install the percona repo
    ansible.builtin.command: 
      dpkg -i /tmp/percona-release_latest.jammy_all.deb
 
  - name: apply the changes
    ansible.builtin.command: 
      apt-get update  

  - name: System, set the swappiness to one
    ansible.builtin.sysctl:
        name: vm.swappiness
        value: "1"
        state: present
        reload: false
  
  